(()=>{
  if(document.querySelector('#wba-btn'))return;
  const btn=document.createElement('button');btn.id='wba-btn';btn.textContent='W AutoFund';
  const panel=document.createElement('aside');panel.id='wba-panel';
  panel.innerHTML='<header><div><b>WB AutoFund</b><small>Автопополнение кампаний</small></div><button id="wba-close">×</button></header><div id="wba-body" class="wba-message">Откройте панель</div>';
  document.documentElement.append(btn,panel);
  let displayDays=7,loadedCampaigns=[];chrome.storage.local.get({displayDays:7},value=>{displayDays=Number(value.displayDays)||7});
  const toggle=()=>{panel.classList.toggle('open');if(panel.classList.contains('open'))load()};
  btn.onclick=toggle;panel.querySelector('#wba-close').onclick=toggle;
  chrome.runtime.onMessage.addListener(m=>m.type==='toggle'&&toggle());
  function selectedWbPeriod(){
    const text=document.body?.innerText||'',match=text.match(/(\d{2})\.(\d{2})\.(\d{4})\s*(?:→|—|–|-)\s*(\d{2})\.(\d{2})\.(\d{4})/);
    if(!match)return null;
    return{from:`${match[3]}-${match[2]}-${match[1]}`,to:`${match[6]}-${match[5]}-${match[4]}`};
  }
  async function load(){
    const body=panel.querySelector('#wba-body');body.className='wba-message';body.textContent='Загрузка…';
    const r=await chrome.runtime.sendMessage({type:'api',path:`/api/dashboard?days=${displayDays}`});
    if(!r?.ok){body.textContent=r?.error||'Настройте подключение через значок расширения';return}
    loadedCampaigns=r.data.campaigns||[];
    body.className='';body.innerHTML='<div class="wba-search"><input type="search" placeholder="Поиск по названию или ID"><select><option value="all">Все кампании</option><option value="enabled">Автопополнение включено</option><option value="setup">Нужно настроить</option></select><small></small></div><div class="wba-cards"></div>';
    const period=document.createElement('label');period.className='wba-period';period.style.cssText='display:flex;flex-direction:column;gap:5px;margin-bottom:10px;color:#777;font-size:11px';period.innerHTML=`Период отображения CTR и ДРР<select><option value="1">Сегодня</option><option value="3">3 дня</option><option value="7">7 дней</option><option value="14">14 дней</option><option value="30">30 дней</option></select>`;const periodSelect=period.querySelector('select');periodSelect.style.cssText='padding:9px;border:1px solid #ddd;border-radius:8px;background:white';periodSelect.value=String(displayDays);periodSelect.onchange=()=>{displayDays=Number(periodSelect.value);chrome.storage.local.set({displayDays});load()};body.prepend(period);
    const input=body.querySelector('.wba-search input'),filter=body.querySelector('.wba-search select'),cards=body.querySelector('.wba-cards'),count=body.querySelector('.wba-search small');
    const render=()=>{const q=input.value.trim().toLocaleLowerCase('ru'),items=r.data.campaigns.filter(c=>(!q||String(c.id).includes(q)||String(c.name).toLocaleLowerCase('ru').includes(q))&&(filter.value==='all'||(filter.value==='enabled'&&c.enabled)||(filter.value==='setup'&&!c.enabled)));count.textContent=`Найдено: ${items.length}`;cards.innerHTML=items.length?items.map(cardHtml).join(''):'<div class="wba-empty">Кампании не найдены</div>';bind(cards)};
    input.oninput=render;filter.onchange=render;render();input.focus();
  }
  function metric(c,key){if(!(c.metrics_available||c.source==='demo'))return '—';if(key==='drr'&&Number(c[key])>=999999)return 'Нет продаж';return `${Number(c[key]||0).toFixed(2)}%`}
  function cardHtml(c){return `<section class="wba-card" data-id="${c.id}"><div class="wba-row"><div><b>${esc(c.name)}</b><div class="wba-meta">ID ${c.id} · ${c.status==='active'?'Активна':'Пауза'}</div></div><button class="wba-edit">${c.enabled?'Включено':'Настроить'}</button></div><div class="wba-metrics"><span>Бюджет<b>${Math.round(c.budget)} ₽</b></span><span>CTR<b>${metric(c,'ctr')}</b></span><span>ДРР<b>${metric(c,'drr')}</b></span></div><form class="wba-form"><div class="wba-grid"><label class="wba-check"><input name="enabled" type="checkbox" ${c.enabled?'checked':''}> Автопополнение</label><label class="wba-check"><input name="use_max_drr" type="checkbox" ${c.use_max_drr!==0?'checked':''}> Учитывать ДРР</label><label>Макс. ДРР, %<input name="max_drr" type="number" step="0.1" value="${c.max_drr??12}"></label><label class="wba-check"><input name="use_min_ctr" type="checkbox" ${c.use_min_ctr!==0?'checked':''}> Учитывать CTR</label><label>Мин. CTR, %<input name="min_ctr" type="number" step="0.1" value="${c.min_ctr??2}"></label><label class="wba-check"><input name="use_min_views" type="checkbox" ${c.use_min_views?'checked':''}> Учитывать показы</label><label>Мин. показов<input name="min_views" type="number" min="0" value="${c.min_views??0}"></label><label class="wba-check"><input name="use_min_orders" type="checkbox" ${c.use_min_orders?'checked':''}> Учитывать заказы</label><label>Мин. заказов<input name="min_orders" type="number" min="0" value="${c.min_orders??0}"></label><label class="wba-check"><input name="use_time_window" type="checkbox" ${c.use_time_window?'checked':''}> Время пополнения по МСК</label><label>С<input name="time_from" type="time" value="${c.time_from??'00:00'}"></label><label>До<input name="time_to" type="time" value="${c.time_to??'23:59'}"></label><label>Порог, ₽<input name="min_budget" type="number" value="${c.min_budget??500}"></label><label>Пополнение, ₽<input name="deposit_amount" type="number" value="${c.deposit_amount??1000}"></label><label>Макс. в сутки<input name="daily_limit" type="number" value="${c.daily_limit??3}"></label></div><button class="wba-save">Сохранить</button></form></section>`}
  function bind(root){root.querySelectorAll('.wba-edit').forEach(b=>b.onclick=()=>b.closest('.wba-card').querySelector('form').classList.toggle('open'));root.querySelectorAll('form').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const card=f.closest('.wba-card'),d=new FormData(f),payload={enabled:d.has('enabled'),use_max_drr:d.has('use_max_drr'),max_drr:d.get('max_drr'),use_min_ctr:d.has('use_min_ctr'),min_ctr:d.get('min_ctr'),use_min_views:d.has('use_min_views'),min_views:d.get('min_views'),use_min_orders:d.has('use_min_orders'),min_orders:d.get('min_orders'),use_time_window:d.has('use_time_window'),time_from:d.get('time_from'),time_to:d.get('time_to'),min_budget:d.get('min_budget'),deposit_amount:d.get('deposit_amount'),daily_limit:d.get('daily_limit'),funding_type:1};const x=await chrome.runtime.sendMessage({type:'api',method:'PUT',path:`/api/campaigns/${card.dataset.id}/rule`,body:payload});x.ok?load():alert(x.error)})}
  function bind(root){
    root.querySelectorAll('.wba-edit').forEach(button=>button.onclick=()=>button.closest('.wba-card').querySelector('form').classList.toggle('open'));
    root.querySelectorAll('form').forEach(form=>{
      const card=form.closest('.wba-card'),campaign=loadedCampaigns.find(item=>String(item.id)===card.dataset.id),grid=form.querySelector('.wba-grid');
      const period=document.createElement('label');period.className='wba-rule-period';period.style.gridColumn='1/-1';period.innerHTML=`Период условий<select name="metrics_days" style="padding:7px;border:1px solid #ddd;border-radius:6px;background:white"><option value="1">Сегодня</option><option value="3">3 дня</option><option value="7">7 дней</option><option value="14">14 дней</option><option value="30">30 дней</option></select><small>Для ДРР, CTR, показов и заказов</small>`;period.querySelector('select').value=String(campaign?.metrics_days||7);
      const resume=document.createElement('label');resume.className='wba-check';resume.style.gridColumn='1/-1';resume.innerHTML=`<input name="auto_resume" type="checkbox" ${campaign?.auto_resume?'checked':''}> Автовозобновление кампании`;
      const resumeLimit=document.createElement('label');resumeLimit.innerHTML=`Макс. возобновлений в сутки<input name="resume_daily_limit" type="number" min="1" max="24" value="${campaign?.resume_daily_limit||1}">`;
      const resumeDelay=document.createElement('label');resumeDelay.innerHTML=`Задержка после пополнения, сек.<input name="resume_delay_seconds" type="number" min="5" max="300" value="${campaign?.resume_delay_seconds||15}">`;
      grid.prepend(resumeDelay);grid.prepend(resumeLimit);grid.prepend(resume);grid.prepend(period);
      const pauseBlock=document.createElement('div');pauseBlock.style.gridColumn='1/-1';pauseBlock.style.borderTop='1px solid #e7e4eb';pauseBlock.style.marginTop='6px';pauseBlock.style.paddingTop='10px';pauseBlock.innerHTML=`<label class="wba-check"><input name="auto_pause" type="checkbox" ${campaign?.auto_pause?'checked':''}> <b>Автоотключение кампании</b></label><small>Если сработает любое отмеченное условие, кампания будет поставлена на паузу. Автопополнение и автовозобновление отключатся.</small>`;
      const pauseDrr=document.createElement('label');pauseDrr.className='wba-check';pauseDrr.innerHTML=`<input name="pause_use_max_drr" type="checkbox" ${campaign?.pause_use_max_drr?'checked':''}> Отключить, если ДРР выше, %<input name="pause_max_drr" type="number" step="0.1" value="${campaign?.pause_max_drr??30}">`;
      const pauseCtr=document.createElement('label');pauseCtr.className='wba-check';pauseCtr.innerHTML=`<input name="pause_use_min_ctr" type="checkbox" ${campaign?.pause_use_min_ctr?'checked':''}> Отключить, если CTR ниже, %<input name="pause_min_ctr" type="number" step="0.1" value="${campaign?.pause_min_ctr??1}">`;
      const pauseViews=document.createElement('label');pauseViews.className='wba-check';pauseViews.innerHTML=`<input name="pause_use_min_views" type="checkbox" ${campaign?.pause_use_min_views?'checked':''}> Отключить, если показы ниже<input name="pause_min_views" type="number" min="0" value="${campaign?.pause_min_views??0}">`;
      const pauseOrders=document.createElement('label');pauseOrders.className='wba-check';pauseOrders.innerHTML=`<input name="pause_use_min_orders" type="checkbox" ${campaign?.pause_use_min_orders?'checked':''}> Отключить, если заказы ниже<input name="pause_min_orders" type="number" min="0" value="${campaign?.pause_min_orders??0}">`;
      grid.append(pauseBlock,pauseDrr,pauseCtr,pauseViews,pauseOrders);
      form.onsubmit=async event=>{event.preventDefault();const data=new FormData(form),payload={enabled:data.has('enabled'),auto_resume:data.has('auto_resume'),resume_daily_limit:data.get('resume_daily_limit'),resume_delay_seconds:data.get('resume_delay_seconds'),use_max_drr:data.has('use_max_drr'),max_drr:data.get('max_drr'),use_min_ctr:data.has('use_min_ctr'),min_ctr:data.get('min_ctr'),use_min_views:data.has('use_min_views'),min_views:data.get('min_views'),use_min_orders:data.has('use_min_orders'),min_orders:data.get('min_orders'),metrics_days:data.get('metrics_days'),use_time_window:data.has('use_time_window'),time_from:data.get('time_from'),time_to:data.get('time_to'),min_budget:data.get('min_budget'),deposit_amount:data.get('deposit_amount'),daily_limit:data.get('daily_limit'),funding_type:1,auto_pause:data.has('auto_pause'),pause_use_max_drr:data.has('pause_use_max_drr'),pause_max_drr:data.get('pause_max_drr'),pause_use_min_ctr:data.has('pause_use_min_ctr'),pause_min_ctr:data.get('pause_min_ctr'),pause_use_min_views:data.has('pause_use_min_views'),pause_min_views:data.get('pause_min_views'),pause_use_min_orders:data.has('pause_use_min_orders'),pause_min_orders:data.get('pause_min_orders')};const result=await chrome.runtime.sendMessage({type:'api',method:'PUT',path:`/api/campaigns/${card.dataset.id}/rule`,body:payload});if(!result.ok)return alert(result.error);if(payload.enabled&&!result.data.live_deposit_ready)alert('Правило сохранено, но реальные пополнения выключены на сервере (WB_LIVE_DEPOSITS).');else if(payload.auto_resume&&!result.data.live_resume_ready)alert('Правило сохранено, но реальное возобновление выключено на сервере (WB_LIVE_RESUME).');else if(payload.auto_pause&&!result.data.live_pause_ready)alert('Правило сохранено, но реальное автоотключение выключено на сервере (WB_LIVE_PAUSE).');load()};
    });
  }
  function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
})();
